exclude_patterns:
    - "versioneer.py"
    - "lettuce/_version.py"
    - "config/"
    - "db/"
    - "dist/"
    - "features/"
    - "**/node_modules/"
    - "script/"
    - "**/spec/"
    - "**/test/"
    - "**/tests/"
    - "Tests/"
    - "**/vendor/"
    - "**/*_test.go"
    - "**/*.d.ts"


